[project]
name = "streambox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "psutil>=7.0.0",
    "requests>=2.32.4",
    "speedtest-cli>=2.1.3",
]
